sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build source branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
  local-dir: public