sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build source branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 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
  keep-history: true
  on:
    branch: source
  local-dir: public